# Generated by Django 4.2.6 on 2023-10-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('description', models.CharField(choices=[('Simple', 'Habitación Simple'), ('Doble', 'Habitación Doble'), ('Triple', 'Habitación Triple'), ('Matrimonial', 'Habitación Matrimonial')], max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bedrooms/', verbose_name='Imagen de la Habitacion')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Bedroom',
                'verbose_name_plural': 'Bedrooms',
            },
        ),
    ]
