# Generated by Django 4.2.6 on 2023-10-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='description',
            field=models.CharField(choices=[('Habitación Simple', 'Habitación Simple'), ('Habitación Doble', 'Habitación Doble'), ('Habitación Triple', 'Habitación Triple'), ('Habitación Matrimonial', 'Habitación Matrimonial')], max_length=30),
        ),
    ]
