# Generated by Django 4.2.6 on 2023-10-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedrooms', '0002_alter_bedroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
