# Generated by Django 4.2.6 on 2023-10-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('bedrooms', '0003_bedroom_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('payment_method', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Efectivo', 'Efectivo')], max_length=30)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('n_adults', models.PositiveIntegerField(default=0)),
                ('n_children', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('type_bedroom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bedrooms.bedroom')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
