# Generated by Django 4.2.6 on 2023-10-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_n_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='n_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
