# Generated by Django 4.2.6 on 2023-10-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_cost_alter_reservation_n_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_days',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
